Improve error messages

diff --git a/.github/workflows/issue-closed.yaml b/.github/workflows/issue-closed.yaml
--- a/.github/workflows/issue-closed.yaml
+++ b/.github/workflows/issue-closed.yaml
@@ -20,7 +20,7 @@ jobs:
         run: |
           if [ -z "$APPLICATION_PRIVATE_KEY" ] || [ -z "$APPLICATION_ID"] ;  then
             gh issue reopen ${{ github.event.issue.number }}
-            gh issue comment ${{ github.event.issue.number }} --body "To continue, we need to have both secrets names `APPLICATION_PRIVATE_KEY` or `APPLICATION_ID` to be set.\n\nPlease set them and try again."
+            gh issue comment ${{ github.event.issue.number }} --body "To continue, we need to have both secrets names `APPLICATION_PRIVATE_KEY` or `APPLICATION_ID` to be set. Please set them and try again."
             exit 1
           fi
         env:
@@ -42,6 +42,7 @@ jobs:
           GITHUB_WORKFLOW_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
           gh issue reopen ${{ github.event.issue.number }}
           gh issue comment ${{ github.event.issue.number }} --body "Failed to generate app token. See output of [workflow run]($GITHUB_WORKFLOW_URL) for details."
+          echo "::error::Failed to generate app token. See output of [workflow run]($GITHUB_WORKFLOW_URL) for details."
           exit 1
         env:
           GH_TOKEN: ${{ github.token }}
@@ -50,61 +51,64 @@ jobs:
     runs-on: ubuntu-latest
     if: contains(github.event.issue.labels.*.name, 'link-azure')
     steps:
-    - name: Validate Azure Credentials
-      run: |
-        #!/usr/bin/env bash
+      - name: Check out the code
+        uses: actions/checkout@v4
 
-        set -euo pipefail
-
-        function missing_secret {
-          # azure_link_issue=$(gh issue list --json 'number' | jq '.[].number' -r | grep link-azure)
-          gh issue reopen ${{ github.event.issue.number }}
-          gh issue comment ${{ github.event.issue.number }} --body "To continue, we need to have Azure credentials set.\n\nPlease set them and try again."
-          exit 1
-        }
-
-        if [[ -z "${{ secrets.AZURE_CLIENT_ID }}" ]] \
-          || [[ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]] \
-          || [[ -z "${{ secrets.AZURE_TENANT_ID }}" ]] \
-          || [[ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]]; then
-          missing_secret
-        fi
-
-        az login --service-principal \
-          --username ${{ secrets.AZURE_CLIENT_ID }} \
-          --password=${{ secrets.AZURE_CLIENT_SECRET }} \
-          --tenant ${{ secrets.AZURE_TENANT_ID }} \
-          --output none
-
-        if [ $? -ne 0 ]; then
-          missing_secret
-        fi
-
-        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-        if [ $? -ne 0 ]; then
-          missing_secret
-        fi
-
-        # If both the client-id and client-secret for the web-app are set, let's test these credentials
-        if [[ -n "${{ secrets.APP_REGISTRATION_APP_ID }}" ]] \
-          && [[ -n "${{ secrets.WEB_APP_CLIENT_SECRET }}"]]; then
-
-            az login --service-principal \
-            --username ${{ secrets.APP_REGISTRATION_APP_ID }} \
-            --password=${{ secrets.WEB_APP_CLIENT_SECRET }} \
+      - name: Validate Azure Credentials
+        run: |
+          #!/usr/bin/env bash
+  
+          set -euo pipefail
+  
+          function missing_secret {
+            gh issue reopen ${{ github.event.issue.number }}
+            gh issue comment ${{ github.event.issue.number }} --body "To continue, we need to have Azure credentials set. Please set them and try again."
+            echo "::error::To continue, we need to have Azure credentials set. Please set them and try again."
+            exit 1
+          }
+  
+          if [[ -z "${{ secrets.AZURE_CLIENT_ID }}" ]] \
+            || [[ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]] \
+            || [[ -z "${{ secrets.AZURE_TENANT_ID }}" ]] \
+            || [[ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]]; then
+            missing_secret
+          fi
+  
+          az login --service-principal \
+            --username ${{ secrets.AZURE_CLIENT_ID }} \
+            --password=${{ secrets.AZURE_CLIENT_SECRET }} \
             --tenant ${{ secrets.AZURE_TENANT_ID }} \
             --output none
-
-            if [ $? -ne 0 ]; then
-              missing_secret
-            fi
-
-            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-            if [ $? -ne 0 ]; then
-              missing_secret
-            fi
-        fi
-      env:
-        GH_TOKEN: ${{ github.token }}
+  
+          if [ $? -ne 0 ]; then
+            missing_secret
+          fi
+  
+          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  
+          if [ $? -ne 0 ]; then
+            missing_secret
+          fi
+  
+          # If both the client-id and client-secret for the web-app are set, let's test these credentials
+          if [[ -n "${{ secrets.APP_REGISTRATION_APP_ID }}" ]] \
+            && [[ -n "${{ secrets.WEB_APP_CLIENT_SECRET }}"]]; then
+  
+              az login --service-principal \
+              --username ${{ secrets.APP_REGISTRATION_APP_ID }} \
+              --password=${{ secrets.WEB_APP_CLIENT_SECRET }} \
+              --tenant ${{ secrets.AZURE_TENANT_ID }} \
+              --output none
+  
+              if [ $? -ne 0 ]; then
+                missing_secret
+              fi
+  
+              az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  
+              if [ $? -ne 0 ]; then
+                missing_secret
+              fi
+          fi
+        env:
+          GH_TOKEN: ${{ github.token }}
